"""Policy decisions: one entry per (year, block). Options 1-5 map to IDEOLOGIES in order.
Effect keys are session-state names; numbers are changes, e.g. headroom=-7.0 means -£7B."""

BLOCKS_PER_YEAR = 4   # three policy decisions, then the Budget
BUDGET_BLOCK = 4
IDEOLOGIES = ['Hard Left', 'Social Democratic', 'Centric', 'Free-Market', 'Fiscal Austerity']

DECISIONS = {
    (1, 1): dict(
        title='The Spring Emergency Statement',
        text='The NHS and police demand an immediate cash injection to clear backlogs.',
        options=[
            '1. (Hard Left / Socialist) Nationalize key utilities and impose steep wealth taxes.',
            '2. (Social Democratic) Borrow heavily to fund public infrastructure and NHS staff.',
            '3. (Centric) Raid defense spending slightly and implement targeted efficiency savings.',
            '4. (Free-Market / Right) Cut red tape, freeze public spending, and rely on private healthcare.',
            '5. (Fiscal Austerity) Enforce immediate spending freezes and departmental cuts.',
        ],
        effects=[
            dict(headroom=1.5, approval=5, market_conf=-16, gilt_yield=0.6, message='Wealth taxes enacted! City bond vigilantes trigger a sell-off.'),
            dict(headroom=-7.0, approval=7, deficit=1.2, message='Keynesian stimulus deployed, but deficit expands.'),
            dict(headroom=-3.5, approval=2, message='Pragmatic compromise found.'),
            dict(market_conf=8, approval=-7, growth=0.2, message='Deregulation path chosen.'),
            dict(headroom=5.0, approval=-12, deficit=-0.9, message='Austerity applied. Headroom recovered, public outraged.'),
        ],
    ),
    (1, 2): dict(
        title='Public Sector Pay & Cabinet Pressure',
        text='Public sector unions are threatening widespread strikes over pay freezes.',
        options=[
            '1. (Hard Left) Meet all union pay demands in full, funded by borrowing.',
            '2. (Social Democratic) Negotiate a generous inflation-matching pay rise linked to tax reforms.',
            '3. (Centric) Offer a balanced compromise settlement to minimize strike disruption.',
            '4. (Free-Market) De-unionize public sectors and introduce competitive private contractor bidding.',
            '5. (Fiscal Austerity) Enforce a strict statutory pay cap and invoke emergency anti-strike laws.',
        ],
        effects=[
            dict(headroom=-8.0, approval=10, deficit=1.4, inflation=0.4, message='Unions appeased, but inflation ticks upward.'),
            dict(headroom=-4.5, approval=6, message='Fair pay settlement reached.'),
            dict(approval=-4, message='Compromise struck with minor disruption.'),
            dict(market_conf=9, approval=-10, message='Private contracting introduced.'),
            dict(approval=-14, market_conf=10, inflation=-0.3, message='Pay cap enforced. Markets pleased, workforce furious.'),
        ],
    ),
    (1, 3): dict(
        title='The Autumn Budget & Fiscal Forecast',
        text='The OBR releases its full annual economic and fiscal outlook.',
        options=[
            '1. (Hard Left) Implement a massive wealth tax and capital controls.',
            '2. (Social Democratic) Invest heavily in green industrial strategy and public R&D.',
            '3. (Centric) Balance tax adjustments with targeted business incentives.',
            '4. (Free-Market) Cut corporation tax to 15% to attract international investment.',
            '5. (Fiscal Austerity) Freeze all departmental budgets in real terms.',
        ],
        effects=[
            dict(headroom=7.0, market_conf=-20, gilt_yield=0.8, message='Wealth tax causes capital flight and gilt sell-off.'),
            dict(growth=0.4, headroom=-4.5, message='Green industrial strategy launched.'),
            dict(growth=0.2, message='Pragmatic budget delivered.'),
            dict(market_conf=12, headroom=-5.5, growth=0.3, message='Corporation tax slashed.'),
            dict(headroom=5.0, deficit=-1.0, approval=-6, message='Budgets frozen.'),
        ],
    ),
    (2, 1): dict(
        title='Welfare & Long-Term Sickness Reform',
        text='Welfare expenditure is spiraling out of control due to rising health claims.',
        options=[
            '1. (Hard Left) Expand universal credit and eliminate benefit sanctions.',
            '2. (Social Democratic) Increase wrap-around employment support and health coaching.',
            '3. (Centric) Streamline welfare administration with moderate criteria checks.',
            '4. (Free-Market) Privatize employment support services and enforce strict work search rules.',
            '5. (Fiscal Austerity) Severely restrict disability benefits to achieve immediate savings.',
        ],
        effects=[
            dict(headroom=-6.0, approval=7, message='Welfare expanded.'),
            dict(growth=0.3, headroom=-3.5, approval=5, message='Health coaching deployed.'),
            dict(headroom=2.0, message='Moderate welfare checks.'),
            dict(headroom=3.5, market_conf=4, approval=-7, message='Employment support outsourced.'),
            dict(headroom=7.5, approval=-16, deficit=-1.1, message='Benefits slashed. Massive public backlash.'),
        ],
    ),
    (2, 2): dict(
        title='Financial Regulation & The City',
        text='London financial institutions demand deregulation to compete globally.',
        options=[
            '1. (Hard Left) Impose strict capital controls and break up high-street mega banks.',
            '2. (Social Democratic) Enforce rigorous ethical and green lending standards on banks.',
            '3. (Centric) Maintain balanced international regulatory standards.',
            '4. (Free-Market) Abolish bankers bonus caps and deregulate financial trading rules.',
            '5. (Fiscal Austerity) Levy an emergency banking sector surcharge to clear debt.',
        ],
        effects=[
            dict(market_conf=-22, gilt_yield=0.7, approval=6, message='Mega banks broken up! Markets plummet.'),
            dict(market_conf=2, approval=4, message='Green lending mandates enacted.'),
            dict(market_conf=3, message='Regulations maintained.'),
            dict(market_conf=14, growth=0.3, approval=-9, message='Bonus caps scrapped.'),
            dict(headroom=5.5, market_conf=-12, message='Emergency banking surcharge levied.'),
        ],
    ),
    (2, 3): dict(
        title='Mid-Term Spending Review',
        text='Local government services face severe funding shortages.',
        options=[
            '1. (Hard Left) Direct central state funding to municipal councils for direct public housing builds.',
            '2. (Social Democratic) Empower metro mayors with universal local tax-raising and transport powers.',
            '3. (Centric) Provide targeted central bailout grants to struggling councils.',
            '4. (Free-Market) Force councils to privatize municipal assets and services.',
            '5. (Fiscal Austerity) Mandate a 10% across-the-board council spending reduction.',
        ],
        effects=[
            dict(headroom=-5.5, approval=7, message='State council housing funded.'),
            dict(approval=6, growth=0.2, message='Metro devolution empowered.'),
            dict(headroom=-4.0, message='Bailout grants issued.'),
            dict(market_conf=6, approval=-7, message='Municipal assets privatized.'),
            dict(headroom=4.5, approval=-10, message='Councils forced into deep cuts.'),
        ],
    ),
    (3, 1): dict(
        title='Regional Transport & Infrastructure',
        text='Major regional rail and bus links require strategic capital investment.',
        options=[
            '1. (Hard Left) Fully public-own and nationalize the entire UK railway network.',
            '2. (Social Democratic) Fund universal bus franchising and regional rail integration.',
            '3. (Centric) Proceed with balanced regional transit upgrades.',
            '4. (Free-Market) Privatize remaining rail infrastructure and invite global private consortia.',
            '5. (Fiscal Austerity) Freeze all major capital transport projects indefinitely.',
        ],
        effects=[
            dict(headroom=-6.5, approval=8, message='Railways fully nationalized.'),
            dict(approval=6, headroom=-4.0, message='Bus networks integrated.'),
            dict(growth=0.2, headroom=-3.0, message='Transit upgrades funded.'),
            dict(market_conf=8, growth=0.3, message='Private rail consortia contracted.'),
            dict(headroom=4.0, approval=-6, message='Infrastructure projects frozen.'),
        ],
    ),
    (3, 2): dict(
        title='Housing Supply & Planning Reform',
        text='A severe housing shortage is crippling affordability for younger voters.',
        options=[
            '1. (Hard Left) Implement rent controls and launch a state housebuilding blitz.',
            '2. (Social Democratic) Mandate high social housing quotas on all private developments.',
            '3. (Centric) Overhaul planning laws to streamline local housing approvals.',
            '4. (Free-Market) Abolish planning restrictions and greenbelt protections entirely.',
            '5. (Fiscal Austerity) Protect greenbelt land and offer no state housing intervention.',
        ],
        effects=[
            dict(approval=9, market_conf=-12, headroom=-5.5, message='Rent controls enacted.'),
            dict(approval=7, growth=0.2, message='Social housing quotas mandated.'),
            dict(growth=0.3, approval=5, message='Planning laws streamlined.'),
            dict(growth=0.5, approval=-9, message='Greenbelt abolished.'),
            dict(approval=-6, message='Greenbelt protected.'),
        ],
    ),
    (3, 3): dict(
        title='Year 3 Autumn Statement',
        text='Mid-term economic check-in with international markets.',
        options=[
            '1. (Hard Left) Institute a maximum wage cap and steep corporate excess profit taxes.',
            '2. (Social Democratic) Issue sovereign green bonds for nationwide renewable grids.',
            '3. (Centric) Provide balanced R&D tax incentives for technology and AI.',
            '4. (Free-Market) Deregulate energy markets and abolish green levies.',
            '5. (Fiscal Austerity) Maintain rigid spending caps and strict debt reduction targets.',
        ],
        effects=[
            dict(approval=5, market_conf=-16, headroom=4.5, message='Excess profit taxes levied.'),
            dict(market_conf=9, growth=0.3, headroom=-4.0, message='Green bonds issued.'),
            dict(growth=0.3, message='Tech incentives established.'),
            dict(market_conf=7, approval=-5, message='Green levies abolished.'),
            dict(headroom=5.0, deficit=-0.8, message='Spending caps maintained.'),
        ],
    ),
    (4, 1): dict(
        title='Global Energy Shock',
        text='Geopolitical tensions cause international gas prices to surge dramatically.',
        options=[
            '1. (Hard Left) Emergency nationalization of energy producers and price freezes.',
            '2. (Social Democratic) Massive state-backed green retrofitting and insulation drive.',
            '3. (Centric) Targeted energy support grants for vulnerable households.',
            '4. (Free-Market) Fast-track North Sea oil and gas drilling licenses.',
            '5. (Fiscal Austerity) Refuse government intervention and let global markets settle.',
        ],
        effects=[
            dict(approval=10, market_conf=-18, headroom=-6.5, message='Energy sector nationalized.'),
            dict(growth=0.3, headroom=-4.5, message='Green retrofit drive launched.'),
            dict(headroom=-3.5, approval=4, message='Energy grants issued.'),
            dict(market_conf=9, approval=-7, message='Drilling licenses approved.'),
            dict(approval=-14, market_conf=-6, message='No intervention.'),
        ],
    ),
    (4, 2): dict(
        title='Trade & International Tariffs',
        text='Major trading partners propose new tariff barriers affecting British exporters.',
        options=[
            '1. (Hard Left) Retaliate with strict protectionist tariffs and import controls.',
            '2. (Social Democratic) Negotiate comprehensive digital and green trade alignment pacts.',
            '3. (Centric) Pursue standard diplomatic trade negotiations.',
            '4. (Free-Market) Unilateral free trade approach with zero tariffs on all imports.',
            '5. (Fiscal Austerity) Absorb trade friction without policy or budget changes.',
        ],
        effects=[
            dict(approval=4, market_conf=-12, inflation=0.5, message='Protectionist tariffs applied.'),
            dict(market_conf=7, growth=0.2, message='Trade pact secured.'),
            dict(growth=0.1, message='Diplomatic trade talks held.'),
            dict(market_conf=10, growth=0.3, approval=-6, message='Unilateral free trade adopted.'),
            dict(growth=-0.2, message='Trade friction ignored.'),
        ],
    ),
    (4, 3): dict(
        title='Year 4 Autumn Statement',
        text='Preparing the economy for the final year leading to the general election.',
        options=[
            '1. (Hard Left) Announce a universal basic income pilot funded by wealth taxes.',
            '2. (Social Democratic) Provide universal retraining vouchers and green startup grants.',
            '3. (Centric) Build up fiscal buffers and moderate treasury reserves.',
            '4. (Free-Market) Cut income tax by 2p across the board to stimulate consumer spending.',
            '5. (Fiscal Austerity) Deliver strict spending reductions to lock in fiscal surpluses.',
        ],
        effects=[
            dict(approval=9, headroom=-7.5, message='UBI pilot launched.'),
            dict(approval=6, growth=0.2, headroom=-3.5, message='Retraining vouchers funded.'),
            dict(headroom=4.5, market_conf=7, message='Fiscal buffers strengthened.'),
            dict(approval=9, headroom=-5.5, message='Income tax cut.'),
            dict(headroom=6.0, deficit=-1.0, message='Surpluses locked in.'),
        ],
    ),
    (5, 1): dict(
        title='Pre-Election Healthcare Push',
        text='Waiting lists remain a major electoral vulnerability as the election approaches.',
        options=[
            '1. (Hard Left) Rebuild NHS capacity strictly via state funding and ban private contractors.',
            '2. (Social Democratic) Launch a massive frontline staff recruitment drive and fund weekend clinics.',
            '3. (Centric) Partner with private healthcare providers to clear backlogs quickly.',
            '4. (Free-Market) Introduce an insurance-based healthcare model with copays.',
            '5. (Fiscal Austerity) Rely on existing NHS efficiencies with no extra funding.',
        ],
        effects=[
            dict(approval=7, headroom=-5.5, message='Private contractors banned.'),
            dict(approval=8, headroom=-4.5, message='Staff recruitment funded.'),
            dict(approval=5, headroom=-3.5, message='Private capacity utilized.'),
            dict(market_conf=9, approval=-16, message='Insurance model introduced. Major backlash.'),
            dict(approval=-7, message='No extra NHS funds.'),
        ],
    ),
    (5, 2): dict(
        title='Final Pre-Election Tax & Spend Adjustments',
        text='Special interest groups lobby heavily ahead of the final manifesto commitments.',
        options=[
            '1. (Hard Left) Implement a wealth tax and fund universal public services.',
            '2. (Social Democratic) Deliver targeted cost-of-living cash support to low-income families.',
            '3. (Centric) Increase defense spending to 2.5% of GDP and protect pensions.',
            '4. (Free-Market) Abolish stamp duty and inheritance tax.',
            '5. (Fiscal Austerity) Hold firm on spending caps and protect fiscal rules.',
        ],
        effects=[
            dict(approval=8, headroom=-4.5, message='Wealth taxes pledged.'),
            dict(approval=9, headroom=-4.5, message='Cost-of-living support delivered.'),
            dict(approval=5, headroom=-3.5, message='Defense and pensions secured.'),
            dict(approval=7, market_conf=7, headroom=-5.5, message='Taxes abolished.'),
            dict(market_conf=9, message='Spending caps held firm.'),
        ],
    ),
    (5, 3): dict(
        title='The General Election Budget & Manifesto Pitch',
        text='The final moment. Deliver your pre-election budget pitch to the country.',
        options=[
            '1. (Hard Left) Radical socialist transformation (Public ownership, wealth taxes, universal services).',
            '2. (Social Democratic) Social democratic renewal (Green investment, NHS expansion, fair taxes).',
            '3. (Centric) Pragmatic center-ground platform (Balanced budgets, moderate reforms, steady growth).',
            '4. (Free-Market) Free-market revolution (Massive tax cuts, deregulation, lean state).',
            '5. (Fiscal Austerity) Uncompromising fiscal orthodoxy (Zero deficit, strict debt reduction).',
        ],
        effects=[
            dict(approval=10, headroom=-5.0, message='Manifesto pitched.'),
            dict(approval=10, growth=0.3, message='Social democratic platform set.'),
            dict(approval=7, market_conf=7, message='Pragmatic platform set.'),
            dict(market_conf=12, approval=3, message='Free-market platform set.'),
            dict(market_conf=16, approval=-10, message='Austerity platform set.'),
        ],
    ),
}
